### ISSUE TITLE
Ignore title in markdown

### ISSUE THREAD

**Issue by achntrl** [williamdclt/git-pretty-pull-request#44]
Hi @williamdclt 

I found a bug in gppr: when your `PULL_REQUEST_TEMPLATE` contains markdown headers (with `#` ) it interprets it as a comment and it is stripped from the real pull request message.

**Comment by williamdclt** [comment]
yup, this issue has been raised by Cedric, and has been fixed like 2 or 3 months ago :) your script probably isn't up to date with the repo

**Comment by achntrl** [comment]
Great !
