### ISSUE TITLE
Nested lists do not work in PR templates

### ISSUE THREAD

**Issue by phacks** [williamdclt/git-pretty-pull-request#58]
Hi @williamdclt!

Just noticed a small bug in the way PR templates are handled in `pretty-pull-request`.

The following template in `PULL_REQUEST_TEMPLATE.md`: 

```md
- [ ] The Definition of Done is respected:
  - [ ] IE 11
  - [ ] Chrome latest
```

is rendered in GitHub:

```md
- [ ] The Definition of Done is respected:
- [ ] IE 11
- [ ] Chrome latest
```

Meaning we’re losing the nested list feature in markdown.

I _think_ the issue comes from these two lines: https://github.com/williamdclt/git-pretty-pull-request/blob/119c15f9c43be484bf38659fb87bc1321a5ac532/git-pretty-pull-request#L136-L137

I could try and give it a go on my own, although if you happen to know exactly what the problem is and can help me submit a PR, that’d be awesome!

Thanks,

Nicolas

**Comment by williamdclt** [comment]
@phacks Good catch! It definitely comes from this: `get_pull_request_message "$1" | trim`
More specifically, the `trim` function seem to trim each line separately :/

Hope you're ready for some `sed` magic :)

I haven't tried it but I think you can update the `trim` function as follow to only trim the start of the first line and the end of the last line: 
```
function trim() {
    sed -e '1s/^[[:space:]]*//' -e '$s/[[:space:]]*$//'
}
```

Downside: if there's a first empty line, it won't be removed

**Comment by phacks** [comment]
@williamdclt Thanks so much, it worked!

Before:

<img width="296" alt="image" src="https://user-images.githubusercontent.com/2587348/35681020-6385de7c-075c-11e8-9f2f-3201bf226aef.png">

After:

<img width="291" alt="image" src="https://user-images.githubusercontent.com/2587348/35680999-5004aacc-075c-11e8-9d22-92611c368996.png">

I’ve submit #59 to fix it in `master` 😃
