### ISSUE TITLE
No fail if a prepush hook fails

### ISSUE THREAD

**Issue by AlbericTrancart** [williamdclt/git-pretty-pull-request#62]
If the project has prepush hooks (such as the ones done with Husky), this will not fail:

```
git commit -m "Something wrong with new ESLint errors"
git pretty-pull-request // includes code-pushing
```

And :tada: there is a commit that fails the tests pushed to the repo :slightly_smiling_face: 

I think the expected behavior is to `git push` before `git pr` but you can miss it

**Comment by VincentLanglet** [comment]
@AlbericTrancart With a fail from the prepush hooks I now get
```
Error running `git fetch`
[PREPROD]: Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
[MASTER]: Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
```

@williamdclt It should fail with a better error message (and not trying to create the pull request)

**Comment by williamdclt** [comment]
It should work better now thanks to your PR, doesn't it @VincentLanglet ?

**Comment by VincentLanglet** [comment]
I agree
![image](https://user-images.githubusercontent.com/9052536/73651725-52162880-4685-11ea-87d3-867783e69dd8.png)

**Comment by williamdclt** [comment]
I was writing a comment asking for a screenshot haha 😄 Perfect, I'll close this, thanks @VincentLanglet !
